// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: io/altessa/serviceinfo/v1/serviceinfo_service.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright 2026 Altessa Solutions Inc. All rights reserved.
// Use of this source code is governed by license that can be found in
// the LICENSE file.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Request for the `GetServiceInfo` method. `ServiceInfo` is a per-connection
/// singleton — the instance answering the call — so there is no `name` to
/// address. The message is intentionally empty for now and exists (instead
/// of `google.protobuf.Empty`) so read options such as a
/// `google.protobuf.FieldMask` can be added later without changing the RPC
/// signature.
public struct Io_Altessa_Serviceinfo_V1_GetServiceInfoRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Response for the `GetServiceInfo` method: a wrapper around the
/// `ServiceInfo` snapshot. A dedicated response message (rather than
/// returning `ServiceInfo` directly) leaves room to add sibling fields
/// later without a breaking change.
public struct Io_Altessa_Serviceinfo_V1_GetServiceInfoResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Runtime information for the instance handling the call.
  public var serviceInfo: Io_Altessa_Serviceinfo_V1_ServiceInfo {
    get {return _serviceInfo ?? Io_Altessa_Serviceinfo_V1_ServiceInfo()}
    set {_serviceInfo = newValue}
  }
  /// Returns true if `serviceInfo` has been explicitly set.
  public var hasServiceInfo: Bool {return self._serviceInfo != nil}
  /// Clears the value of `serviceInfo`. Subsequent reads from it will return its default value.
  public mutating func clearServiceInfo() {self._serviceInfo = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _serviceInfo: Io_Altessa_Serviceinfo_V1_ServiceInfo? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "io.altessa.serviceinfo.v1"

extension Io_Altessa_Serviceinfo_V1_GetServiceInfoRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetServiceInfoRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Io_Altessa_Serviceinfo_V1_GetServiceInfoRequest, rhs: Io_Altessa_Serviceinfo_V1_GetServiceInfoRequest) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Io_Altessa_Serviceinfo_V1_GetServiceInfoResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetServiceInfoResponse"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "service_info"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._serviceInfo) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._serviceInfo {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Io_Altessa_Serviceinfo_V1_GetServiceInfoResponse, rhs: Io_Altessa_Serviceinfo_V1_GetServiceInfoResponse) -> Bool {
    if lhs._serviceInfo != rhs._serviceInfo {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
