// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: type/v1/contact.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright 2026 Altessa Solutions Inc. All rights reserved.
// Use of this source code is governed by license that can be found in
// the LICENSE file.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// A single contact endpoint (phone, email, social handle, …). The variant
/// of `value` carries both the payload and the category — consumers
/// dispatch on the oneof case instead of inspecting a separate type tag.
/// Phone numbers use google.type.PhoneNumber so country code and extension
/// are preserved structurally; email and social handles are opaque strings
/// whose format is not enforced by this schema.
public struct Io_Altessa_Type_V1_Contact: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Stable identifier of the contact within its issuing system. Opaque to
  /// consumers; used to address this contact in per-element operations on
  /// parent messages (e.g. updating one entry in a `repeated Contact` list
  /// without replacing the whole list). Assigned at creation and never
  /// changes afterwards — to "rename" a contact, delete and recreate it.
  public var id: String = String()

  /// The contact endpoint. Exactly one variant MUST be set; an unset
  /// `value` is a malformed Contact and producers SHOULD reject it.
  public var value: Io_Altessa_Type_V1_Contact.OneOf_Value? = nil

  /// Email address.
  public var email: String {
    get {
      if case .email(let v)? = value {return v}
      return String()
    }
    set {value = .email(newValue)}
  }

  /// Telephone number with structured country code, extension, and
  /// short-code support.
  public var phone: Google_Type_PhoneNumber {
    get {
      if case .phone(let v)? = value {return v}
      return Google_Type_PhoneNumber()
    }
    set {value = .phone(newValue)}
  }

  /// Social media handle (e.g. "@alice" on a network identified
  /// out-of-band).
  public var socialHandle: String {
    get {
      if case .socialHandle(let v)? = value {return v}
      return String()
    }
    set {value = .socialHandle(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  /// The contact endpoint. Exactly one variant MUST be set; an unset
  /// `value` is a malformed Contact and producers SHOULD reject it.
  public enum OneOf_Value: Equatable, Sendable {
    /// Email address.
    case email(String)
    /// Telephone number with structured country code, extension, and
    /// short-code support.
    case phone(Google_Type_PhoneNumber)
    /// Social media handle (e.g. "@alice" on a network identified
    /// out-of-band).
    case socialHandle(String)

  }

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "io.altessa.type.v1"

extension Io_Altessa_Type_V1_Contact: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Contact"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
    2: .same(proto: "email"),
    3: .same(proto: "phone"),
    4: .standard(proto: "social_handle"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 2: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.value != nil {try decoder.handleConflictingOneOf()}
          self.value = .email(v)
        }
      }()
      case 3: try {
        var v: Google_Type_PhoneNumber?
        var hadOneofValue = false
        if let current = self.value {
          hadOneofValue = true
          if case .phone(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.value = .phone(v)
        }
      }()
      case 4: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.value != nil {try decoder.handleConflictingOneOf()}
          self.value = .socialHandle(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    switch self.value {
    case .email?: try {
      guard case .email(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    }()
    case .phone?: try {
      guard case .phone(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case .socialHandle?: try {
      guard case .socialHandle(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Io_Altessa_Type_V1_Contact, rhs: Io_Altessa_Type_V1_Contact) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.value != rhs.value {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
