// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: type/v1/gender.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright 2026 Altessa Solutions Inc. All rights reserved.
// Use of this source code is governed by license that can be found in
// the LICENSE file.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Biological sex of a person. Intentionally minimal — extend the schema in
/// downstream code if richer gender identity is needed (this enum stays
/// stable and small so it can be reused across unrelated services).
///
/// Stability (AIP-180): closed and frozen at v1. New values are NOT
/// expected; consumers MAY assume the value set will not grow.
public enum Io_Altessa_Type_V1_Gender: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int

  /// Sentinel default. Treat as "not provided" rather than as a value.
  case unspecified // = 0
  case male // = 1
  case female // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .male
    case 2: self = .female
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .male: return 1
    case .female: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Io_Altessa_Type_V1_Gender] = [
    .unspecified,
    .male,
    .female,
  ]

}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension Io_Altessa_Type_V1_Gender: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "GENDER_UNSPECIFIED"),
    1: .same(proto: "GENDER_MALE"),
    2: .same(proto: "GENDER_FEMALE"),
  ]
}
