// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: type/v1/money_range.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright 2026 Altessa Solutions Inc. All rights reserved.
// Use of this source code is governed by license that can be found in
// the LICENSE file.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Inclusive range between two monetary amounts. Both bounds MUST share
/// the same `currency_code` and `min` MUST NOT exceed `max`; producers
/// are responsible for enforcing both invariants. A zero-length range
/// (`min == max`) is valid and represents a single amount.
///
/// `MoneyRange` has no notion of open or half-open ranges — both bounds
/// are required. For one-sided thresholds ("amounts above $100",
/// "amounts up to $1000"), use a single `google.type.Money` on the
/// surrounding message instead of synthesising a sentinel `min` / `max`.
///
/// Negative amounts are permitted (credits, refunds, signed P&L). The
/// ordering invariant still applies: `min <= max` as signed values
/// (e.g. min = -100, max = -10 is well-formed; min = -10, max = -100 is
/// not).
public struct Io_Altessa_Type_V1_MoneyRange: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Lower bound, inclusive.
  public var min: Google_Type_Money {
    get {return _min ?? Google_Type_Money()}
    set {_min = newValue}
  }
  /// Returns true if `min` has been explicitly set.
  public var hasMin: Bool {return self._min != nil}
  /// Clears the value of `min`. Subsequent reads from it will return its default value.
  public mutating func clearMin() {self._min = nil}

  /// Upper bound, inclusive. MUST be in the same currency as `min` and
  /// greater than or equal to `min`.
  public var max: Google_Type_Money {
    get {return _max ?? Google_Type_Money()}
    set {_max = newValue}
  }
  /// Returns true if `max` has been explicitly set.
  public var hasMax: Bool {return self._max != nil}
  /// Clears the value of `max`. Subsequent reads from it will return its default value.
  public mutating func clearMax() {self._max = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _min: Google_Type_Money? = nil
  fileprivate var _max: Google_Type_Money? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "io.altessa.type.v1"

extension Io_Altessa_Type_V1_MoneyRange: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".MoneyRange"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "min"),
    2: .same(proto: "max"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._min) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._max) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._min {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._max {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Io_Altessa_Type_V1_MoneyRange, rhs: Io_Altessa_Type_V1_MoneyRange) -> Bool {
    if lhs._min != rhs._min {return false}
    if lhs._max != rhs._max {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
