// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: type/v1/pagination.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright 2026 Altessa Solutions Inc. All rights reserved.
// Use of this source code is governed by license that can be found in
// the LICENSE file.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Pagination parameters for list requests. Field names and types follow
/// https://google.aip.dev/158; the message additionally carries an
/// `offset` field for collections where token-based continuation is
/// inconvenient (small, slow-changing, or admin-only lists).
/// `page_token` and `offset` are mutually exclusive — set at most one.
///
/// Request-side only. This message covers the parameters a client sends;
/// services define their own list-response shape — by convention a
/// repeated items field at position 1 plus a `string next_page_token`
/// that callers feed back into `page_token` on the following request.
/// There is intentionally no shared `PaginationResponse` here because
/// the items-field type and optional total counts vary per service.
///
/// `page_size` semantics: zero requests the service-defined default of
/// 1000 items. Servers MUST cap it at an implementation-defined maximum
/// and MUST return INVALID_ARGUMENT for negative values. The
/// NON_EMPTY_DEFAULT annotation signals that the server substitutes a
/// concrete non-empty value (1000) when the client leaves the field
/// unset.
///
/// `page_token` semantics: opaque string minted by the server. Clients
/// MUST round-trip it verbatim and MUST NOT decode or synthesise one.
/// Servers MAY invalidate tokens at any time (schema migrations,
/// snapshot expiry) and SHOULD respond with INVALID_ARGUMENT or a typed
/// error rather than silently restarting from the first page.
///
/// `offset` semantics: number of items to skip from the start of the
/// unpaginated result set. Prefer `page_token` for large or rapidly
/// changing collections — `offset` re-scans the result set and is
/// subject to drift when items are inserted or deleted between calls.
public struct Io_Altessa_Type_V1_Pagination: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Maximum number of items the server should return. Zero requests
  /// the service-defined default (1000); negative values yield
  /// INVALID_ARGUMENT.
  public var pageSize: Int32 = 0

  /// Opaque continuation token returned in a previous list response.
  /// Empty (the default) requests the first page. Mutually exclusive
  /// with `offset`.
  public var pageToken: String = String()

  /// Number of items to skip from the start of the unpaginated result
  /// set. Zero (the proto3 default) requests the first page. Mutually
  /// exclusive with `page_token`.
  public var offset: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "io.altessa.type.v1"

extension Io_Altessa_Type_V1_Pagination: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Pagination"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "page_size"),
    2: .standard(proto: "page_token"),
    3: .same(proto: "offset"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.pageSize) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.pageToken) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.offset) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.pageSize != 0 {
      try visitor.visitSingularInt32Field(value: self.pageSize, fieldNumber: 1)
    }
    if !self.pageToken.isEmpty {
      try visitor.visitSingularStringField(value: self.pageToken, fieldNumber: 2)
    }
    if self.offset != 0 {
      try visitor.visitSingularInt32Field(value: self.offset, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Io_Altessa_Type_V1_Pagination, rhs: Io_Altessa_Type_V1_Pagination) -> Bool {
    if lhs.pageSize != rhs.pageSize {return false}
    if lhs.pageToken != rhs.pageToken {return false}
    if lhs.offset != rhs.offset {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
