// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: type/v1/sort_direction.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright 2026 Altessa Solutions Inc. All rights reserved.
// Use of this source code is governed by license that can be found in
// the LICENSE file.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Ordering direction for list / search responses. Typically appears in
/// a list request next to a service-specific sort-field selector, e.g.
///
///   message ListUsersRequest {
///     string sort_by = 1;             // service-defined field name
///     SortDirection direction = 2;
///     Pagination pagination = 3;
///   }
///
/// For multi-key ordering or per-field direction, services define their
/// own richer sort message — this enum stays a single-direction
/// primitive on purpose.
///
/// Zero value: unlike most enums in this package, `SortDirection` does
/// not have an `_UNSPECIFIED` zero value. `SORT_DIRECTION_ASC = 0` is
/// the natural default (matches SQL `ORDER BY` without `DESC`), so a
/// distinct sentinel would add noise without information. This is the
/// only exception in `type/v1` (see `buf.yaml` for the lint waiver).
///
/// Stability (AIP-180): closed and frozen at v1. There are only two
/// meaningful directions for a single sort key; consumers MAY assume
/// the value set will not grow.
public enum Io_Altessa_Type_V1_SortDirection: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int

  /// Ascending: A→Z, 0→9, oldest first. This is the default.
  case asc // = 0

  /// Descending: Z→A, 9→0, newest first.
  case desc // = 1
  case UNRECOGNIZED(Int)

  public init() {
    self = .asc
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .asc
    case 1: self = .desc
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .asc: return 0
    case .desc: return 1
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Io_Altessa_Type_V1_SortDirection] = [
    .asc,
    .desc,
  ]

}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension Io_Altessa_Type_V1_SortDirection: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "SORT_DIRECTION_ASC"),
    1: .same(proto: "SORT_DIRECTION_DESC"),
  ]
}
