// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: services/serviceinfo/v1/serviceinfo.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright 2026 Altessa Solutions Inc. All rights reserved.
// Use of this source code is governed by license that can be found in
// the LICENSE file.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Detailed information about a running service instance: identification,
/// versioning, build details, leadership status, and arbitrary metadata.
/// Every field is populated by the server; clients MUST treat the message
/// as read-only.
///
/// Deployment guidance: this payload is intended for ops / diagnostic
/// use. It contains no end-user PII by design, but `metadata` MAY carry
/// environment details (region, cluster, feature flags) that you don't
/// always want exposed publicly — production deployments SHOULD gate
/// `ServiceInfoService.Get` behind authn / authz when the service is
/// not in a trusted network.
///
/// Snapshot semantics: `uptime` (and to a lesser extent `leader` and
/// `leader_id`) are evaluated at request time. Two consecutive calls
/// will return slightly different values; clients that need precise
/// duration arithmetic SHOULD subtract `start_time` from their own
/// clock instead of relying on `uptime`.
public struct Io_Altessa_Serviceinfo_V1_ServiceInfo: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The canonical name of the service (e.g., "user-service", "billing-api").
  public var serviceName: String {
    get {return _storage._serviceName}
    set {_uniqueStorage()._serviceName = newValue}
  }

  /// Human-readable description of the service and its purpose.
  public var serviceDescription: String {
    get {return _storage._serviceDescription ?? String()}
    set {_uniqueStorage()._serviceDescription = newValue}
  }
  /// Returns true if `serviceDescription` has been explicitly set.
  public var hasServiceDescription: Bool {return _storage._serviceDescription != nil}
  /// Clears the value of `serviceDescription`. Subsequent reads from it will return its default value.
  public mutating func clearServiceDescription() {_uniqueStorage()._serviceDescription = nil}

  /// Unique identifier for this specific instance of the service (e.g., a UUID or hostname-pid).
  public var serviceID: String {
    get {return _storage._serviceID ?? String()}
    set {_uniqueStorage()._serviceID = newValue}
  }
  /// Returns true if `serviceID` has been explicitly set.
  public var hasServiceID: Bool {return _storage._serviceID != nil}
  /// Clears the value of `serviceID`. Subsequent reads from it will return its default value.
  public mutating func clearServiceID() {_uniqueStorage()._serviceID = nil}

  /// Whether this service instance is currently the leader in a distributed
  /// system. True if this instance is the leader, false otherwise. (Per
  /// AIP-140 boolean fields omit the `is_` prefix.)
  public var leader: Bool {
    get {return _storage._leader}
    set {_uniqueStorage()._leader = newValue}
  }

  /// The full version string of the service (e.g., "1.2.3-alpha+build.123").
  /// This may include semantic version, pre-release, and build metadata.
  public var fullVersion: String {
    get {return _storage._fullVersion}
    set {_uniqueStorage()._fullVersion = newValue}
  }

  /// The structured semantic version of the service.
  public var semanticVersion: Io_Altessa_Serviceinfo_V1_ServiceInfo.SemanticVersion {
    get {return _storage._semanticVersion ?? Io_Altessa_Serviceinfo_V1_ServiceInfo.SemanticVersion()}
    set {_uniqueStorage()._semanticVersion = newValue}
  }
  /// Returns true if `semanticVersion` has been explicitly set.
  public var hasSemanticVersion: Bool {return _storage._semanticVersion != nil}
  /// Clears the value of `semanticVersion`. Subsequent reads from it will return its default value.
  public mutating func clearSemanticVersion() {_uniqueStorage()._semanticVersion = nil}

  /// Wall-clock time at which the service binary was built.
  public var buildTime: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _storage._buildTime ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_uniqueStorage()._buildTime = newValue}
  }
  /// Returns true if `buildTime` has been explicitly set.
  public var hasBuildTime: Bool {return _storage._buildTime != nil}
  /// Clears the value of `buildTime`. Subsequent reads from it will return its default value.
  public mutating func clearBuildTime() {_uniqueStorage()._buildTime = nil}

  /// Name of the source code branch from which this service instance was built (e.g., "main", "develop").
  public var branch: String {
    get {return _storage._branch ?? String()}
    set {_uniqueStorage()._branch = newValue}
  }
  /// Returns true if `branch` has been explicitly set.
  public var hasBranch: Bool {return _storage._branch != nil}
  /// Clears the value of `branch`. Subsequent reads from it will return its default value.
  public mutating func clearBranch() {_uniqueStorage()._branch = nil}

  /// Full Git commit hash (SHA) of the source code revision from which this service instance was built.
  public var commit: String {
    get {return _storage._commit ?? String()}
    set {_uniqueStorage()._commit = newValue}
  }
  /// Returns true if `commit` has been explicitly set.
  public var hasCommit: Bool {return _storage._commit != nil}
  /// Clears the value of `commit`. Subsequent reads from it will return its default value.
  public mutating func clearCommit() {_uniqueStorage()._commit = nil}

  /// Build tags or flags used during the compilation of the service.
  public var buildTags: String {
    get {return _storage._buildTags ?? String()}
    set {_uniqueStorage()._buildTags = newValue}
  }
  /// Returns true if `buildTags` has been explicitly set.
  public var hasBuildTags: Bool {return _storage._buildTags != nil}
  /// Clears the value of `buildTags`. Subsequent reads from it will return its default value.
  public mutating func clearBuildTags() {_uniqueStorage()._buildTags = nil}

  /// A collection of key-value pairs for additional, arbitrary metadata about the service instance.
  /// Keys and values are strings. Maximum 100 entries allowed.
  public var metadata: Dictionary<String,String> {
    get {return _storage._metadata}
    set {_uniqueStorage()._metadata = newValue}
  }

  /// Identifier of the current leader instance if this node is not the leader.
  /// This is useful for clients to discover the active leader.
  public var leaderID: String {
    get {return _storage._leaderID ?? String()}
    set {_uniqueStorage()._leaderID = newValue}
  }
  /// Returns true if `leaderID` has been explicitly set.
  public var hasLeaderID: Bool {return _storage._leaderID != nil}
  /// Clears the value of `leaderID`. Subsequent reads from it will return its default value.
  public mutating func clearLeaderID() {_uniqueStorage()._leaderID = nil}

  /// Wall-clock time at which this service instance started.
  public var startTime: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _storage._startTime ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_uniqueStorage()._startTime = newValue}
  }
  /// Returns true if `startTime` has been explicitly set.
  public var hasStartTime: Bool {return _storage._startTime != nil}
  /// Clears the value of `startTime`. Subsequent reads from it will return its default value.
  public mutating func clearStartTime() {_uniqueStorage()._startTime = nil}

  /// Time elapsed since `start_time`. Computed by the server on each request;
  /// clients should treat it as advisory and recompute from `start_time` if
  /// they need precise duration arithmetic.
  public var uptime: SwiftProtobuf.Google_Protobuf_Duration {
    get {return _storage._uptime ?? SwiftProtobuf.Google_Protobuf_Duration()}
    set {_uniqueStorage()._uptime = newValue}
  }
  /// Returns true if `uptime` has been explicitly set.
  public var hasUptime: Bool {return _storage._uptime != nil}
  /// Clears the value of `uptime`. Subsequent reads from it will return its default value.
  public mutating func clearUptime() {_uniqueStorage()._uptime = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  /// Defines a version conforming to the Semantic Versioning 2.0.0 specification (semver.org).
  public struct SemanticVersion: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// The MAJOR version, incremented for incompatible API changes.
    public var major: UInt32 = 0

    /// The MINOR version, incremented for adding functionality in a backward-compatible manner.
    public var minor: UInt32 = 0

    /// The PATCH version, incremented for backward-compatible bug fixes.
    public var patch: UInt32 = 0

    /// Pre-release identifier (e.g., "alpha", "beta.1").
    /// A series of dot-separated identifiers immediately following the patch version.
    public var preRelease: String {
      get {return _preRelease ?? String()}
      set {_preRelease = newValue}
    }
    /// Returns true if `preRelease` has been explicitly set.
    public var hasPreRelease: Bool {return self._preRelease != nil}
    /// Clears the value of `preRelease`. Subsequent reads from it will return its default value.
    public mutating func clearPreRelease() {self._preRelease = nil}

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _preRelease: String? = nil
  }

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "io.altessa.serviceinfo.v1"

extension Io_Altessa_Serviceinfo_V1_ServiceInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ServiceInfo"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(
      reservedNames: [],
      reservedRanges: [12..<13],
      numberNameMappings: [
        1: .standard(proto: "service_name"),
        2: .standard(proto: "service_description"),
        3: .standard(proto: "service_id"),
        4: .same(proto: "leader"),
        5: .standard(proto: "full_version"),
        6: .standard(proto: "semantic_version"),
        7: .standard(proto: "build_time"),
        8: .same(proto: "branch"),
        9: .same(proto: "commit"),
        10: .standard(proto: "build_tags"),
        11: .same(proto: "metadata"),
        13: .standard(proto: "leader_id"),
        14: .standard(proto: "start_time"),
        15: .same(proto: "uptime"),
  ])

  fileprivate class _StorageClass {
    var _serviceName: String = String()
    var _serviceDescription: String? = nil
    var _serviceID: String? = nil
    var _leader: Bool = false
    var _fullVersion: String = String()
    var _semanticVersion: Io_Altessa_Serviceinfo_V1_ServiceInfo.SemanticVersion? = nil
    var _buildTime: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
    var _branch: String? = nil
    var _commit: String? = nil
    var _buildTags: String? = nil
    var _metadata: Dictionary<String,String> = [:]
    var _leaderID: String? = nil
    var _startTime: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
    var _uptime: SwiftProtobuf.Google_Protobuf_Duration? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _serviceName = source._serviceName
      _serviceDescription = source._serviceDescription
      _serviceID = source._serviceID
      _leader = source._leader
      _fullVersion = source._fullVersion
      _semanticVersion = source._semanticVersion
      _buildTime = source._buildTime
      _branch = source._branch
      _commit = source._commit
      _buildTags = source._buildTags
      _metadata = source._metadata
      _leaderID = source._leaderID
      _startTime = source._startTime
      _uptime = source._uptime
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularStringField(value: &_storage._serviceName) }()
        case 2: try { try decoder.decodeSingularStringField(value: &_storage._serviceDescription) }()
        case 3: try { try decoder.decodeSingularStringField(value: &_storage._serviceID) }()
        case 4: try { try decoder.decodeSingularBoolField(value: &_storage._leader) }()
        case 5: try { try decoder.decodeSingularStringField(value: &_storage._fullVersion) }()
        case 6: try { try decoder.decodeSingularMessageField(value: &_storage._semanticVersion) }()
        case 7: try { try decoder.decodeSingularMessageField(value: &_storage._buildTime) }()
        case 8: try { try decoder.decodeSingularStringField(value: &_storage._branch) }()
        case 9: try { try decoder.decodeSingularStringField(value: &_storage._commit) }()
        case 10: try { try decoder.decodeSingularStringField(value: &_storage._buildTags) }()
        case 11: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &_storage._metadata) }()
        case 13: try { try decoder.decodeSingularStringField(value: &_storage._leaderID) }()
        case 14: try { try decoder.decodeSingularMessageField(value: &_storage._startTime) }()
        case 15: try { try decoder.decodeSingularMessageField(value: &_storage._uptime) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if !_storage._serviceName.isEmpty {
        try visitor.visitSingularStringField(value: _storage._serviceName, fieldNumber: 1)
      }
      try { if let v = _storage._serviceDescription {
        try visitor.visitSingularStringField(value: v, fieldNumber: 2)
      } }()
      try { if let v = _storage._serviceID {
        try visitor.visitSingularStringField(value: v, fieldNumber: 3)
      } }()
      if _storage._leader != false {
        try visitor.visitSingularBoolField(value: _storage._leader, fieldNumber: 4)
      }
      if !_storage._fullVersion.isEmpty {
        try visitor.visitSingularStringField(value: _storage._fullVersion, fieldNumber: 5)
      }
      try { if let v = _storage._semanticVersion {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
      } }()
      try { if let v = _storage._buildTime {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
      } }()
      try { if let v = _storage._branch {
        try visitor.visitSingularStringField(value: v, fieldNumber: 8)
      } }()
      try { if let v = _storage._commit {
        try visitor.visitSingularStringField(value: v, fieldNumber: 9)
      } }()
      try { if let v = _storage._buildTags {
        try visitor.visitSingularStringField(value: v, fieldNumber: 10)
      } }()
      if !_storage._metadata.isEmpty {
        try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: _storage._metadata, fieldNumber: 11)
      }
      try { if let v = _storage._leaderID {
        try visitor.visitSingularStringField(value: v, fieldNumber: 13)
      } }()
      try { if let v = _storage._startTime {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 14)
      } }()
      try { if let v = _storage._uptime {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 15)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Io_Altessa_Serviceinfo_V1_ServiceInfo, rhs: Io_Altessa_Serviceinfo_V1_ServiceInfo) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._serviceName != rhs_storage._serviceName {return false}
        if _storage._serviceDescription != rhs_storage._serviceDescription {return false}
        if _storage._serviceID != rhs_storage._serviceID {return false}
        if _storage._leader != rhs_storage._leader {return false}
        if _storage._fullVersion != rhs_storage._fullVersion {return false}
        if _storage._semanticVersion != rhs_storage._semanticVersion {return false}
        if _storage._buildTime != rhs_storage._buildTime {return false}
        if _storage._branch != rhs_storage._branch {return false}
        if _storage._commit != rhs_storage._commit {return false}
        if _storage._buildTags != rhs_storage._buildTags {return false}
        if _storage._metadata != rhs_storage._metadata {return false}
        if _storage._leaderID != rhs_storage._leaderID {return false}
        if _storage._startTime != rhs_storage._startTime {return false}
        if _storage._uptime != rhs_storage._uptime {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Io_Altessa_Serviceinfo_V1_ServiceInfo.SemanticVersion: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Io_Altessa_Serviceinfo_V1_ServiceInfo.protoMessageName + ".SemanticVersion"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "major"),
    2: .same(proto: "minor"),
    3: .same(proto: "patch"),
    4: .standard(proto: "pre_release"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.major) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.minor) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.patch) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._preRelease) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.major != 0 {
      try visitor.visitSingularUInt32Field(value: self.major, fieldNumber: 1)
    }
    if self.minor != 0 {
      try visitor.visitSingularUInt32Field(value: self.minor, fieldNumber: 2)
    }
    if self.patch != 0 {
      try visitor.visitSingularUInt32Field(value: self.patch, fieldNumber: 3)
    }
    try { if let v = self._preRelease {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Io_Altessa_Serviceinfo_V1_ServiceInfo.SemanticVersion, rhs: Io_Altessa_Serviceinfo_V1_ServiceInfo.SemanticVersion) -> Bool {
    if lhs.major != rhs.major {return false}
    if lhs.minor != rhs.minor {return false}
    if lhs.patch != rhs.patch {return false}
    if lhs._preRelease != rhs._preRelease {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
