// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: io/altessa/type/v1/location_privacy.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright 2026 Altessa Solutions Inc. All rights reserved.
// Use of this source code is governed by license that can be found in
// the LICENSE file.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Privacy level applied to a user's geolocation before it is exposed to
/// other users or downstream services. The actor that holds raw coordinates
/// is expected to coarsen them according to this enum before propagation.
///
/// The schema only mandates the precision tier — the exact coarsening
/// method (truncation, round-to-nearest, geohash, k-anonymity bucket,
/// …) is the producer's choice. Producers SHOULD pick one method and
/// apply it deterministically per user, so the user's exposed position
/// does not jitter between requests with no real-world movement (this
/// would otherwise leak the true position via averaging).
///
/// Stability (AIP-180): closed and frozen at v1. New values are NOT
/// expected; new precision tiers belong in domain-specific schemas
/// rather than as additions here.
public enum Io_Altessa_Type_V1_LocationPrivacy: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int

  /// Sentinel default. When received from a client in a request, servers
  /// SHOULD reject with INVALID_ARGUMENT so the privacy choice is
  /// explicit. When read from persistent storage, servers SHOULD apply
  /// the most restrictive interpretation (= treat as LOCATION_PRIVACY_OFF).
  case unspecified // = 0

  /// Tracking disabled. Coordinates must not be persisted.
  case off // = 1

  /// Coordinates are persisted but not exposed to other users. The owner can
  /// search relative to their own position; they remain non-discoverable to
  /// peers.
  case `private` // = 2

  /// City-scale precision: coordinates rounded to ~10 km (≈ 0.1°).
  case publicCity // = 3

  /// Neighbourhood-scale precision: coordinates rounded to ~1 km (≈ 0.01°).
  case publicApproximate // = 4

  /// Full precision (~10 m). Coordinates are exposed as captured.
  case publicExact // = 5
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .off
    case 2: self = .private
    case 3: self = .publicCity
    case 4: self = .publicApproximate
    case 5: self = .publicExact
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .off: return 1
    case .private: return 2
    case .publicCity: return 3
    case .publicApproximate: return 4
    case .publicExact: return 5
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Io_Altessa_Type_V1_LocationPrivacy] = [
    .unspecified,
    .off,
    .private,
    .publicCity,
    .publicApproximate,
    .publicExact,
  ]

}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension Io_Altessa_Type_V1_LocationPrivacy: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "LOCATION_PRIVACY_UNSPECIFIED"),
    1: .same(proto: "LOCATION_PRIVACY_OFF"),
    2: .same(proto: "LOCATION_PRIVACY_PRIVATE"),
    3: .same(proto: "LOCATION_PRIVACY_PUBLIC_CITY"),
    4: .same(proto: "LOCATION_PRIVACY_PUBLIC_APPROXIMATE"),
    5: .same(proto: "LOCATION_PRIVACY_PUBLIC_EXACT"),
  ]
}
