// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: io/altessa/type/v1/organization_type.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright 2026 Altessa Solutions Inc. All rights reserved.
// Use of this source code is governed by license that can be found in
// the LICENSE file.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Legal form of an organization at a coarse level. Use this when the
/// distinction "natural person doing business" vs "registered legal entity"
/// is enough; jurisdiction-specific subtypes (ИП vs самозанятый, LLC vs
/// C-corp, …) belong in a domain-specific schema.
///
/// Stability (AIP-180): closed and frozen at v1. New values are NOT
/// expected; jurisdiction-specific subtypes are added in domain
/// schemas, not here.
public enum Io_Altessa_Type_V1_OrganizationType: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int

  /// Sentinel default. Treat as "not provided" rather than as a value.
  case unspecified // = 0

  /// Natural person operating as a sole proprietor / individual entrepreneur
  /// (e.g. ИП in RU, sole trader in UK, sole proprietorship in US).
  case individual // = 1

  /// Registered legal entity distinct from its owners (e.g. ООО / АО in RU,
  /// LLC / Inc. in US, GmbH / AG in DE).
  case organization // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .individual
    case 2: self = .organization
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .individual: return 1
    case .organization: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Io_Altessa_Type_V1_OrganizationType] = [
    .unspecified,
    .individual,
    .organization,
  ]

}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension Io_Altessa_Type_V1_OrganizationType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "ORGANIZATION_TYPE_UNSPECIFIED"),
    1: .same(proto: "ORGANIZATION_TYPE_INDIVIDUAL"),
    2: .same(proto: "ORGANIZATION_TYPE_ORGANIZATION"),
  ]
}
