// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: badrequest/v1/badrequest.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright 2026 Altessa Solutions Inc. All rights reserved.
// Use of this source code is governed by license that can be found in
// the LICENSE file.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Defines a general error structure for requests that are malformed or contain invalid data.
/// It typically includes a list of specific field violations that caused the request to be rejected.
/// This message is often used as a detail payload for `google.rpc.Status` when the error code is `INVALID_ARGUMENT`.
public struct Io_Altessa_Badrequest_V1_BadRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// A list of individual field violations that contributed to the bad request.
  public var fieldViolations: [Io_Altessa_Badrequest_V1_FieldViolation] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Defines a specific issue with a single field in the request message.
/// It provides details about which field was problematic and why.
public struct Io_Altessa_Badrequest_V1_FieldViolation: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The dot-separated path to the field that caused the violation.
  /// For example, "user.address.street" or "items[2].name".
  public var fieldPath: String {
    get {return _fieldPath ?? String()}
    set {_fieldPath = newValue}
  }
  /// Returns true if `fieldPath` has been explicitly set.
  public var hasFieldPath: Bool {return self._fieldPath != nil}
  /// Clears the value of `fieldPath`. Subsequent reads from it will return its default value.
  public mutating func clearFieldPath() {self._fieldPath = nil}

  /// Human-readable message describing the violation.
  /// This should be specific to the field and the error condition.
  public var message: String {
    get {return _message ?? String()}
    set {_message = newValue}
  }
  /// Returns true if `message` has been explicitly set.
  public var hasMessage: Bool {return self._message != nil}
  /// Clears the value of `message`. Subsequent reads from it will return its default value.
  public mutating func clearMessage() {self._message = nil}

  /// Application-specific error code or identifier for this type of violation.
  /// This can be used by clients for programmatic error handling.
  public var code: String {
    get {return _code ?? String()}
    set {_code = newValue}
  }
  /// Returns true if `code` has been explicitly set.
  public var hasCode: Bool {return self._code != nil}
  /// Clears the value of `code`. Subsequent reads from it will return its default value.
  public mutating func clearCode() {self._code = nil}

  /// Structured representation of the path to the field that caused the violation.
  /// This provides more detailed information than `field_path` and can be used for
  /// more precise error handling or display.
  public var fieldPathComponents: [Io_Altessa_Badrequest_V1_FieldPathComponent] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _fieldPath: String? = nil
  fileprivate var _message: String? = nil
  fileprivate var _code: String? = nil
}

/// Defines a single segment in the path to a violated field.
/// It provides details about the field name, number, type, and, if applicable, its index in a repeated field or its key in a map.
public struct Io_Altessa_Badrequest_V1_FieldPathComponent: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Field number as defined in the .proto file.
  public var number: Int32 {
    get {return _number ?? 0}
    set {_number = newValue}
  }
  /// Returns true if `number` has been explicitly set.
  public var hasNumber: Bool {return self._number != nil}
  /// Clears the value of `number`. Subsequent reads from it will return its default value.
  public mutating func clearNumber() {self._number = nil}

  /// Name of the field as defined in the .proto file.
  public var name: String {
    get {return _name ?? String()}
    set {_name = newValue}
  }
  /// Returns true if `name` has been explicitly set.
  public var hasName: Bool {return self._name != nil}
  /// Clears the value of `name`. Subsequent reads from it will return its default value.
  public mutating func clearName() {self._name = nil}

  /// Data type of the field.
  public var type: SwiftProtobuf.Google_Protobuf_FieldDescriptorProto.TypeEnum {
    get {return _type ?? .double}
    set {_type = newValue}
  }
  /// Returns true if `type` has been explicitly set.
  public var hasType: Bool {return self._type != nil}
  /// Clears the value of `type`. Subsequent reads from it will return its default value.
  public mutating func clearType() {self._type = nil}

  /// For map fields, specifies the data type of the map keys.
  public var mapKeyType: SwiftProtobuf.Google_Protobuf_FieldDescriptorProto.TypeEnum {
    get {return _mapKeyType ?? .double}
    set {_mapKeyType = newValue}
  }
  /// Returns true if `mapKeyType` has been explicitly set.
  public var hasMapKeyType: Bool {return self._mapKeyType != nil}
  /// Clears the value of `mapKeyType`. Subsequent reads from it will return its default value.
  public mutating func clearMapKeyType() {self._mapKeyType = nil}

  /// For map fields, specifies the data type of the map values.
  public var mapValueType: SwiftProtobuf.Google_Protobuf_FieldDescriptorProto.TypeEnum {
    get {return _mapValueType ?? .double}
    set {_mapValueType = newValue}
  }
  /// Returns true if `mapValueType` has been explicitly set.
  public var hasMapValueType: Bool {return self._mapValueType != nil}
  /// Clears the value of `mapValueType`. Subsequent reads from it will return its default value.
  public mutating func clearMapValueType() {self._mapValueType = nil}

  /// Indicates whether the field is a repeated field (i.e., an array or list).
  public var isRepeated: Bool {
    get {return _isRepeated ?? false}
    set {_isRepeated = newValue}
  }
  /// Returns true if `isRepeated` has been explicitly set.
  public var hasIsRepeated: Bool {return self._isRepeated != nil}
  /// Clears the value of `isRepeated`. Subsequent reads from it will return its default value.
  public mutating func clearIsRepeated() {self._isRepeated = nil}

  /// For repeated fields, the 0-based index of the element that caused the violation.
  public var repeatedIndex: UInt64 {
    get {return _repeatedIndex ?? 0}
    set {_repeatedIndex = newValue}
  }
  /// Returns true if `repeatedIndex` has been explicitly set.
  public var hasRepeatedIndex: Bool {return self._repeatedIndex != nil}
  /// Clears the value of `repeatedIndex`. Subsequent reads from it will return its default value.
  public mutating func clearRepeatedIndex() {self._repeatedIndex = nil}

  /// If the field is a map, this `oneof` specifies the key of the map entry that caused the violation.
  /// Only one of the `key` fields will be set, corresponding to the actual type of the map key.
  public var mapKey: Io_Altessa_Badrequest_V1_FieldPathComponent.OneOf_MapKey? = nil

  /// The index if the map key is treated as an array index (less common for proto maps).
  public var index: UInt64 {
    get {
      if case .index(let v)? = mapKey {return v}
      return 0
    }
    set {mapKey = .index(newValue)}
  }

  /// The map key, if its type is `bool`.
  public var boolKey: Bool {
    get {
      if case .boolKey(let v)? = mapKey {return v}
      return false
    }
    set {mapKey = .boolKey(newValue)}
  }

  /// The map key, if its type is `int32`, `int64`, `sint32`, `sint64`, `sfixed32`, or `sfixed64`.
  public var intKey: Int64 {
    get {
      if case .intKey(let v)? = mapKey {return v}
      return 0
    }
    set {mapKey = .intKey(newValue)}
  }

  /// The map key, if its type is `uint32`, `uint64`, `fixed32`, or `fixed64`.
  public var uintKey: UInt64 {
    get {
      if case .uintKey(let v)? = mapKey {return v}
      return 0
    }
    set {mapKey = .uintKey(newValue)}
  }

  /// The map key, if its type is `string`.
  public var stringKey: String {
    get {
      if case .stringKey(let v)? = mapKey {return v}
      return String()
    }
    set {mapKey = .stringKey(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  /// If the field is a map, this `oneof` specifies the key of the map entry that caused the violation.
  /// Only one of the `key` fields will be set, corresponding to the actual type of the map key.
  public enum OneOf_MapKey: Equatable, Sendable {
    /// The index if the map key is treated as an array index (less common for proto maps).
    case index(UInt64)
    /// The map key, if its type is `bool`.
    case boolKey(Bool)
    /// The map key, if its type is `int32`, `int64`, `sint32`, `sint64`, `sfixed32`, or `sfixed64`.
    case intKey(Int64)
    /// The map key, if its type is `uint32`, `uint64`, `fixed32`, or `fixed64`.
    case uintKey(UInt64)
    /// The map key, if its type is `string`.
    case stringKey(String)

  }

  public init() {}

  fileprivate var _number: Int32? = nil
  fileprivate var _name: String? = nil
  fileprivate var _type: SwiftProtobuf.Google_Protobuf_FieldDescriptorProto.TypeEnum? = nil
  fileprivate var _mapKeyType: SwiftProtobuf.Google_Protobuf_FieldDescriptorProto.TypeEnum? = nil
  fileprivate var _mapValueType: SwiftProtobuf.Google_Protobuf_FieldDescriptorProto.TypeEnum? = nil
  fileprivate var _isRepeated: Bool? = nil
  fileprivate var _repeatedIndex: UInt64? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "io.altessa.badrequest.v1"

extension Io_Altessa_Badrequest_V1_BadRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".BadRequest"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "field_violations"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.fieldViolations) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.fieldViolations.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.fieldViolations, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Io_Altessa_Badrequest_V1_BadRequest, rhs: Io_Altessa_Badrequest_V1_BadRequest) -> Bool {
    if lhs.fieldViolations != rhs.fieldViolations {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Io_Altessa_Badrequest_V1_FieldViolation: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FieldViolation"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "field_path"),
    2: .same(proto: "message"),
    3: .same(proto: "code"),
    4: .standard(proto: "field_path_components"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._fieldPath) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._message) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._code) }()
      case 4: try { try decoder.decodeRepeatedMessageField(value: &self.fieldPathComponents) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._fieldPath {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._message {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._code {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    if !self.fieldPathComponents.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.fieldPathComponents, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Io_Altessa_Badrequest_V1_FieldViolation, rhs: Io_Altessa_Badrequest_V1_FieldViolation) -> Bool {
    if lhs._fieldPath != rhs._fieldPath {return false}
    if lhs._message != rhs._message {return false}
    if lhs._code != rhs._code {return false}
    if lhs.fieldPathComponents != rhs.fieldPathComponents {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Io_Altessa_Badrequest_V1_FieldPathComponent: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FieldPathComponent"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "number"),
    2: .same(proto: "name"),
    3: .same(proto: "type"),
    4: .standard(proto: "map_key_type"),
    5: .standard(proto: "map_value_type"),
    6: .standard(proto: "is_repeated"),
    7: .standard(proto: "repeated_index"),
    8: .same(proto: "index"),
    9: .standard(proto: "bool_key"),
    10: .standard(proto: "int_key"),
    11: .standard(proto: "uint_key"),
    12: .standard(proto: "string_key"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self._number) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._name) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self._type) }()
      case 4: try { try decoder.decodeSingularEnumField(value: &self._mapKeyType) }()
      case 5: try { try decoder.decodeSingularEnumField(value: &self._mapValueType) }()
      case 6: try { try decoder.decodeSingularBoolField(value: &self._isRepeated) }()
      case 7: try { try decoder.decodeSingularUInt64Field(value: &self._repeatedIndex) }()
      case 8: try {
        var v: UInt64?
        try decoder.decodeSingularUInt64Field(value: &v)
        if let v = v {
          if self.mapKey != nil {try decoder.handleConflictingOneOf()}
          self.mapKey = .index(v)
        }
      }()
      case 9: try {
        var v: Bool?
        try decoder.decodeSingularBoolField(value: &v)
        if let v = v {
          if self.mapKey != nil {try decoder.handleConflictingOneOf()}
          self.mapKey = .boolKey(v)
        }
      }()
      case 10: try {
        var v: Int64?
        try decoder.decodeSingularInt64Field(value: &v)
        if let v = v {
          if self.mapKey != nil {try decoder.handleConflictingOneOf()}
          self.mapKey = .intKey(v)
        }
      }()
      case 11: try {
        var v: UInt64?
        try decoder.decodeSingularUInt64Field(value: &v)
        if let v = v {
          if self.mapKey != nil {try decoder.handleConflictingOneOf()}
          self.mapKey = .uintKey(v)
        }
      }()
      case 12: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.mapKey != nil {try decoder.handleConflictingOneOf()}
          self.mapKey = .stringKey(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._number {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._name {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._type {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._mapKeyType {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._mapValueType {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._isRepeated {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._repeatedIndex {
      try visitor.visitSingularUInt64Field(value: v, fieldNumber: 7)
    } }()
    switch self.mapKey {
    case .index?: try {
      guard case .index(let v)? = self.mapKey else { preconditionFailure() }
      try visitor.visitSingularUInt64Field(value: v, fieldNumber: 8)
    }()
    case .boolKey?: try {
      guard case .boolKey(let v)? = self.mapKey else { preconditionFailure() }
      try visitor.visitSingularBoolField(value: v, fieldNumber: 9)
    }()
    case .intKey?: try {
      guard case .intKey(let v)? = self.mapKey else { preconditionFailure() }
      try visitor.visitSingularInt64Field(value: v, fieldNumber: 10)
    }()
    case .uintKey?: try {
      guard case .uintKey(let v)? = self.mapKey else { preconditionFailure() }
      try visitor.visitSingularUInt64Field(value: v, fieldNumber: 11)
    }()
    case .stringKey?: try {
      guard case .stringKey(let v)? = self.mapKey else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 12)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Io_Altessa_Badrequest_V1_FieldPathComponent, rhs: Io_Altessa_Badrequest_V1_FieldPathComponent) -> Bool {
    if lhs._number != rhs._number {return false}
    if lhs._name != rhs._name {return false}
    if lhs._type != rhs._type {return false}
    if lhs._mapKeyType != rhs._mapKeyType {return false}
    if lhs._mapValueType != rhs._mapValueType {return false}
    if lhs._isRepeated != rhs._isRepeated {return false}
    if lhs._repeatedIndex != rhs._repeatedIndex {return false}
    if lhs.mapKey != rhs.mapKey {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
